import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
// For default weight (400) and all styles
import "@fontsource/poppins"; 

// For a specific weight
import "@fontsource/poppins/700.css"; 

// For a specific weight and style (e.g., italic)
import "@fontsource/poppins/700-italic.css"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main>
        <html>
          <body>
        <SidebarTrigger />
        {children}
        </body>
        </html>
      </main>
    </SidebarProvider>
  )
}
